before:
  hooks:
    - go generate ./...
builds:
  - main: .
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - main: ./go-tom-pdf/.
    binary: tom-pdf
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

nfpm:
  formats:
    - deb
  vendor: "https://github.com/jansorg/tom"
  homepage: "https://github.com/jansorg/tom"
  maintainer: "Joachim Ansorg <tom@ja-dev.eu>"
  description: "Tom is a command line tool to track time"
  license: ""
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  bindir: /usr/bin
  files:
    "scripts/completions/tom.sh": "/etc/bash_completion.d/tom.sh"
  replacements:
    linux: Linux
    windows: Windows
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
  overrides:
    deb:
      dependencies:
        - bash-completion

archive:
  replacements:
    linux: Linux
    windows: Windows
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^prep:'
      - '^wip'
