before:
  hooks:
    - go generate ./...
builds:
  -
    main: .
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  -
    main: ./go-tom-pdf/.
    binary: tom-pdf
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

nfpm:
  formats:
    - deb
  vendor: "ja-dev.eu"
  homepage: "https://github.com/jansorg/tom"
  description: "Tom is a command line tool to track time",
  license: ""
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  bindir: /usr/bin
  files:
    "scripts/completions/": "/etc/bash_completion.d"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^wip'
