before:
  hooks:
    - go generate ./...
builds:
  -
    main: .
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  -
    main: ./go-tom-pdf/.
    binary: tom-pdf
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^wip'
